apiRules:
- include:
    uidRegex: ^eDIA
    type: Namespace
- include:
    uidRegex: ^TASK
    type: Namespace
- exclude:
    uidRegex: ^eDIA.EditorUtils
    type: Namespace
- exclude:
    uidRegex: ^eDIA.Utilities
    type: Namespace
- exclude:
    uidRegex: .*
    type: Namespace