### YamlMime:ManagedReference
items:
- uid: eDIA.ExperimentManager.TrialSequenceValuesContainer
  commentId: T:eDIA.ExperimentManager.TrialSequenceValuesContainer
  id: ExperimentManager.TrialSequenceValuesContainer
  parent: eDIA
  children:
  - eDIA.ExperimentManager.TrialSequenceValuesContainer.trialSequenceValues
  langs:
  - csharp
  - vb
  name: ExperimentManager.TrialSequenceValuesContainer
  nameWithType: ExperimentManager.TrialSequenceValuesContainer
  fullName: eDIA.ExperimentManager.TrialSequenceValuesContainer
  type: Class
  source:
    id: TrialSequenceValuesContainer
    path: ''
    startLine: 523
  assemblies:
  - cs.temp.dll
  namespace: eDIA
  summary: Container for (de)serializing a list to JSON
  example: []
  syntax:
    content: public class TrialSequenceValuesContainer
    content.vb: Public Class TrialSequenceValuesContainer
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: eDIA.ExperimentManager.TrialSequenceValuesContainer.trialSequenceValues
  commentId: F:eDIA.ExperimentManager.TrialSequenceValuesContainer.trialSequenceValues
  id: trialSequenceValues
  parent: eDIA.ExperimentManager.TrialSequenceValuesContainer
  langs:
  - csharp
  - vb
  name: trialSequenceValues
  nameWithType: ExperimentManager.TrialSequenceValuesContainer.trialSequenceValues
  fullName: eDIA.ExperimentManager.TrialSequenceValuesContainer.trialSequenceValues
  type: Field
  source:
    id: trialSequenceValues
    path: ''
    startLine: 524
  assemblies:
  - cs.temp.dll
  namespace: eDIA
  syntax:
    content: public List<ExperimentManager.TrialSequenceValues> trialSequenceValues
    return:
      type: Global.List{eDIA.ExperimentManager.TrialSequenceValues}
    content.vb: Public trialSequenceValues As List(Of ExperimentManager.TrialSequenceValues)
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: eDIA
  commentId: N:eDIA
  name: eDIA
  nameWithType: eDIA
  fullName: eDIA
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: Global.List{eDIA.ExperimentManager.TrialSequenceValues}
  commentId: '!:Global.List{eDIA.ExperimentManager.TrialSequenceValues}'
  definition: Global.List`1
  name: List<ExperimentManager.TrialSequenceValues>
  nameWithType: List<ExperimentManager.TrialSequenceValues>
  fullName: List<eDIA.ExperimentManager.TrialSequenceValues>
  nameWithType.vb: List(Of ExperimentManager.TrialSequenceValues)
  fullName.vb: List(Of eDIA.ExperimentManager.TrialSequenceValues)
  name.vb: List(Of ExperimentManager.TrialSequenceValues)
  spec.csharp:
  - uid: Global.List`1
    name: List
    nameWithType: List
    fullName: List
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - uid: eDIA.ExperimentManager.TrialSequenceValues
    name: ExperimentManager.TrialSequenceValues
    nameWithType: ExperimentManager.TrialSequenceValues
    fullName: eDIA.ExperimentManager.TrialSequenceValues
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: Global.List`1
    name: List
    nameWithType: List
    fullName: List
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - uid: eDIA.ExperimentManager.TrialSequenceValues
    name: ExperimentManager.TrialSequenceValues
    nameWithType: ExperimentManager.TrialSequenceValues
    fullName: eDIA.ExperimentManager.TrialSequenceValues
  - name: )
    nameWithType: )
    fullName: )
- uid: Global.List`1
  isExternal: true
  name: List<>
  nameWithType: List<>
  fullName: List<>
  nameWithType.vb: List(Of )
  fullName.vb: List(Of )
  name.vb: List(Of )
  spec.csharp:
  - uid: Global.List`1
    name: List
    nameWithType: List
    fullName: List
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - name: ''
    nameWithType: ''
    fullName: ''
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: Global.List`1
    name: List
    nameWithType: List
    fullName: List
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: ''
    nameWithType: ''
    fullName: ''
  - name: )
    nameWithType: )
    fullName: )
