### YamlMime:ManagedReference
items:
- uid: eDIA.SettingsDeclaration
  commentId: T:eDIA.SettingsDeclaration
  id: SettingsDeclaration
  parent: eDIA
  children:
  - eDIA.SettingsDeclaration.InteractiveInteractor
  - eDIA.SettingsDeclaration.language
  - eDIA.SettingsDeclaration.localConfigDirectoryName
  - eDIA.SettingsDeclaration.pathToLogfiles
  - eDIA.SettingsDeclaration.screenResolution
  - eDIA.SettingsDeclaration.VisableInteractor
  - eDIA.SettingsDeclaration.volume
  langs:
  - csharp
  - vb
  name: SettingsDeclaration
  nameWithType: SettingsDeclaration
  fullName: eDIA.SettingsDeclaration
  type: Class
  source:
    id: SettingsDeclaration
    path: ''
    startLine: 6669
  assemblies:
  - cs.temp.dll
  namespace: eDIA
  summary: 'Container to hold main settings of the application '
  example: []
  syntax:
    content: >-
      [Serializable]

      public class SettingsDeclaration
    content.vb: >-
      <Serializable>

      Public Class SettingsDeclaration
  inheritance:
  - System.Object
  attributes:
  - type: System.SerializableAttribute
    ctor: System.SerializableAttribute.#ctor
    arguments: []
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: eDIA.SettingsDeclaration.VisableInteractor
  commentId: F:eDIA.SettingsDeclaration.VisableInteractor
  id: VisableInteractor
  parent: eDIA.SettingsDeclaration
  langs:
  - csharp
  - vb
  name: VisableInteractor
  nameWithType: SettingsDeclaration.VisableInteractor
  fullName: eDIA.SettingsDeclaration.VisableInteractor
  type: Field
  source:
    id: VisableInteractor
    path: ''
    startLine: 6672
  assemblies:
  - cs.temp.dll
  namespace: eDIA
  syntax:
    content: public Constants.Interactor VisableInteractor
    return:
      type: eDIA.Constants.Interactor
    content.vb: Public VisableInteractor As Constants.Interactor
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: eDIA.SettingsDeclaration.InteractiveInteractor
  commentId: F:eDIA.SettingsDeclaration.InteractiveInteractor
  id: InteractiveInteractor
  parent: eDIA.SettingsDeclaration
  langs:
  - csharp
  - vb
  name: InteractiveInteractor
  nameWithType: SettingsDeclaration.InteractiveInteractor
  fullName: eDIA.SettingsDeclaration.InteractiveInteractor
  type: Field
  source:
    id: InteractiveInteractor
    path: ''
    startLine: 6673
  assemblies:
  - cs.temp.dll
  namespace: eDIA
  syntax:
    content: public Constants.Interactor InteractiveInteractor
    return:
      type: eDIA.Constants.Interactor
    content.vb: Public InteractiveInteractor As Constants.Interactor
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: eDIA.SettingsDeclaration.screenResolution
  commentId: F:eDIA.SettingsDeclaration.screenResolution
  id: screenResolution
  parent: eDIA.SettingsDeclaration
  langs:
  - csharp
  - vb
  name: screenResolution
  nameWithType: SettingsDeclaration.screenResolution
  fullName: eDIA.SettingsDeclaration.screenResolution
  type: Field
  source:
    id: screenResolution
    path: ''
    startLine: 6674
  assemblies:
  - cs.temp.dll
  namespace: eDIA
  syntax:
    content: public int screenResolution
    return:
      type: System.Int32
    content.vb: Public screenResolution As Integer
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: eDIA.SettingsDeclaration.volume
  commentId: F:eDIA.SettingsDeclaration.volume
  id: volume
  parent: eDIA.SettingsDeclaration
  langs:
  - csharp
  - vb
  name: volume
  nameWithType: SettingsDeclaration.volume
  fullName: eDIA.SettingsDeclaration.volume
  type: Field
  source:
    id: volume
    path: ''
    startLine: 6675
  assemblies:
  - cs.temp.dll
  namespace: eDIA
  syntax:
    content: public float volume
    return:
      type: System.Single
    content.vb: Public volume As Single
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: eDIA.SettingsDeclaration.language
  commentId: F:eDIA.SettingsDeclaration.language
  id: language
  parent: eDIA.SettingsDeclaration
  langs:
  - csharp
  - vb
  name: language
  nameWithType: SettingsDeclaration.language
  fullName: eDIA.SettingsDeclaration.language
  type: Field
  source:
    id: language
    path: ''
    startLine: 6676
  assemblies:
  - cs.temp.dll
  namespace: eDIA
  syntax:
    content: public Constants.Languages language
    return:
      type: eDIA.Constants.Languages
    content.vb: Public language As Constants.Languages
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: eDIA.SettingsDeclaration.pathToLogfiles
  commentId: F:eDIA.SettingsDeclaration.pathToLogfiles
  id: pathToLogfiles
  parent: eDIA.SettingsDeclaration
  langs:
  - csharp
  - vb
  name: pathToLogfiles
  nameWithType: SettingsDeclaration.pathToLogfiles
  fullName: eDIA.SettingsDeclaration.pathToLogfiles
  type: Field
  source:
    id: pathToLogfiles
    path: ''
    startLine: 6678
  assemblies:
  - cs.temp.dll
  namespace: eDIA
  syntax:
    content: public string pathToLogfiles
    return:
      type: System.String
    content.vb: Public pathToLogfiles As String
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: eDIA.SettingsDeclaration.localConfigDirectoryName
  commentId: F:eDIA.SettingsDeclaration.localConfigDirectoryName
  id: localConfigDirectoryName
  parent: eDIA.SettingsDeclaration
  langs:
  - csharp
  - vb
  name: localConfigDirectoryName
  nameWithType: SettingsDeclaration.localConfigDirectoryName
  fullName: eDIA.SettingsDeclaration.localConfigDirectoryName
  type: Field
  source:
    id: localConfigDirectoryName
    path: ''
    startLine: 6679
  assemblies:
  - cs.temp.dll
  namespace: eDIA
  syntax:
    content: public static string localConfigDirectoryName
    return:
      type: System.String
    content.vb: Public Shared localConfigDirectoryName As String
  modifiers.csharp:
  - public
  - static
  modifiers.vb:
  - Public
  - Shared
references:
- uid: eDIA
  commentId: N:eDIA
  name: eDIA
  nameWithType: eDIA
  fullName: eDIA
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: eDIA.Constants.Interactor
  commentId: T:eDIA.Constants.Interactor
  parent: eDIA
  name: Constants.Interactor
  nameWithType: Constants.Interactor
  fullName: eDIA.Constants.Interactor
- uid: System.Int32
  commentId: T:System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.Single
  commentId: T:System.Single
  parent: System
  isExternal: true
  name: Single
  nameWithType: Single
  fullName: System.Single
- uid: eDIA.Constants.Languages
  commentId: T:eDIA.Constants.Languages
  parent: eDIA
  name: Constants.Languages
  nameWithType: Constants.Languages
  fullName: eDIA.Constants.Languages
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
