### YamlMime:ManagedReference
items:
- uid: eDIA.TaskManagerBase.TaskSettingsContainer
  commentId: T:eDIA.TaskManagerBase.TaskSettingsContainer
  id: TaskManagerBase.TaskSettingsContainer
  parent: eDIA
  children:
  - eDIA.TaskManagerBase.TaskSettingsContainer.taskSettings
  langs:
  - csharp
  - vb
  name: TaskManagerBase.TaskSettingsContainer
  nameWithType: TaskManagerBase.TaskSettingsContainer
  fullName: eDIA.TaskManagerBase.TaskSettingsContainer
  type: Class
  source:
    id: TaskSettingsContainer
    path: ''
    startLine: 910
  assemblies:
  - cs.temp.dll
  namespace: eDIA
  summary: "\nEach task has it&apos;s own settings. <br />\nContainer to deserialize the <code>TaskSettings.json</code> file in\n"
  example: []
  syntax:
    content: >-
      [Serializable]

      public class TaskSettingsContainer
    content.vb: >-
      <Serializable>

      Public Class TaskSettingsContainer
  inheritance:
  - System.Object
  attributes:
  - type: System.SerializableAttribute
    ctor: System.SerializableAttribute.#ctor
    arguments: []
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: eDIA.TaskManagerBase.TaskSettingsContainer.taskSettings
  commentId: F:eDIA.TaskManagerBase.TaskSettingsContainer.taskSettings
  id: taskSettings
  parent: eDIA.TaskManagerBase.TaskSettingsContainer
  langs:
  - csharp
  - vb
  name: taskSettings
  nameWithType: TaskManagerBase.TaskSettingsContainer.taskSettings
  fullName: eDIA.TaskManagerBase.TaskSettingsContainer.taskSettings
  type: Field
  source:
    id: taskSettings
    path: ''
    startLine: 912
  assemblies:
  - cs.temp.dll
  namespace: eDIA
  syntax:
    content: public List<ExperimentManager.SettingsTuple> taskSettings
    return:
      type: Global.List{eDIA.ExperimentManager.SettingsTuple}
    content.vb: Public taskSettings As List(Of ExperimentManager.SettingsTuple)
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: eDIA
  commentId: N:eDIA
  name: eDIA
  nameWithType: eDIA
  fullName: eDIA
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: Global.List{eDIA.ExperimentManager.SettingsTuple}
  commentId: '!:Global.List{eDIA.ExperimentManager.SettingsTuple}'
  definition: Global.List`1
  name: List<ExperimentManager.SettingsTuple>
  nameWithType: List<ExperimentManager.SettingsTuple>
  fullName: List<eDIA.ExperimentManager.SettingsTuple>
  nameWithType.vb: List(Of ExperimentManager.SettingsTuple)
  fullName.vb: List(Of eDIA.ExperimentManager.SettingsTuple)
  name.vb: List(Of ExperimentManager.SettingsTuple)
  spec.csharp:
  - uid: Global.List`1
    name: List
    nameWithType: List
    fullName: List
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - uid: eDIA.ExperimentManager.SettingsTuple
    name: ExperimentManager.SettingsTuple
    nameWithType: ExperimentManager.SettingsTuple
    fullName: eDIA.ExperimentManager.SettingsTuple
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: Global.List`1
    name: List
    nameWithType: List
    fullName: List
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - uid: eDIA.ExperimentManager.SettingsTuple
    name: ExperimentManager.SettingsTuple
    nameWithType: ExperimentManager.SettingsTuple
    fullName: eDIA.ExperimentManager.SettingsTuple
  - name: )
    nameWithType: )
    fullName: )
- uid: Global.List`1
  isExternal: true
  name: List<>
  nameWithType: List<>
  fullName: List<>
  nameWithType.vb: List(Of )
  fullName.vb: List(Of )
  name.vb: List(Of )
  spec.csharp:
  - uid: Global.List`1
    name: List
    nameWithType: List
    fullName: List
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - name: ''
    nameWithType: ''
    fullName: ''
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: Global.List`1
    name: List
    nameWithType: List
    fullName: List
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: ''
    nameWithType: ''
    fullName: ''
  - name: )
    nameWithType: )
    fullName: )
