### YamlMime:ManagedReference
items:
- uid: eDIA.SettingsTuple
  commentId: T:eDIA.SettingsTuple
  id: SettingsTuple
  parent: eDIA
  children:
  - eDIA.SettingsTuple.key
  - eDIA.SettingsTuple.value
  langs:
  - csharp
  - vb
  name: SettingsTuple
  nameWithType: SettingsTuple
  fullName: eDIA.SettingsTuple
  type: Class
  source:
    id: SettingsTuple
    path: ''
    startLine: 6517
  assemblies:
  - cs.temp.dll
  namespace: eDIA
  summary: Tuple of strings, this is serializable in the inspector and dictionaries are not
  example: []
  syntax:
    content: >-
      [Serializable]

      public class SettingsTuple
    content.vb: >-
      <Serializable>

      Public Class SettingsTuple
  inheritance:
  - System.Object
  attributes:
  - type: System.SerializableAttribute
    ctor: System.SerializableAttribute.#ctor
    arguments: []
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: eDIA.SettingsTuple.key
  commentId: F:eDIA.SettingsTuple.key
  id: key
  parent: eDIA.SettingsTuple
  langs:
  - csharp
  - vb
  name: key
  nameWithType: SettingsTuple.key
  fullName: eDIA.SettingsTuple.key
  type: Field
  source:
    id: key
    path: ''
    startLine: 6520
  assemblies:
  - cs.temp.dll
  namespace: eDIA
  syntax:
    content: public string key
    return:
      type: System.String
    content.vb: Public key As String
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: eDIA.SettingsTuple.value
  commentId: F:eDIA.SettingsTuple.value
  id: value
  parent: eDIA.SettingsTuple
  langs:
  - csharp
  - vb
  name: value
  nameWithType: SettingsTuple.value
  fullName: eDIA.SettingsTuple.value
  type: Field
  source:
    id: value
    path: ''
    startLine: 6521
  assemblies:
  - cs.temp.dll
  namespace: eDIA
  syntax:
    content: public string value
    return:
      type: System.String
    content.vb: Public value As String
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: eDIA
  commentId: N:eDIA
  name: eDIA
  nameWithType: eDIA
  fullName: eDIA
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
