### YamlMime:ManagedReference
items:
- uid: eDIA.ExperimentConfig
  commentId: T:eDIA.ExperimentConfig
  id: ExperimentConfig
  parent: eDIA
  children:
  - eDIA.ExperimentConfig.experiment
  - eDIA.ExperimentConfig.experimenter
  - eDIA.ExperimentConfig.GetExperimentSummary
  - eDIA.ExperimentConfig.GetParticipantDetailsAsDict
  - eDIA.ExperimentConfig.GetParticipantID
  - eDIA.ExperimentConfig.isReady
  - eDIA.ExperimentConfig.participant_details
  - eDIA.ExperimentConfig.session_number
  langs:
  - csharp
  - vb
  name: ExperimentConfig
  nameWithType: ExperimentConfig
  fullName: eDIA.ExperimentConfig
  type: Class
  source:
    id: ExperimentConfig
    path: ''
    startLine: 6550
  assemblies:
  - cs.temp.dll
  namespace: eDIA
  summary: Experiment config container
  example: []
  syntax:
    content: >-
      [Serializable]

      public class ExperimentConfig
    content.vb: >-
      <Serializable>

      Public Class ExperimentConfig
  inheritance:
  - System.Object
  attributes:
  - type: System.SerializableAttribute
    ctor: System.SerializableAttribute.#ctor
    arguments: []
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: eDIA.ExperimentConfig.experiment
  commentId: F:eDIA.ExperimentConfig.experiment
  id: experiment
  parent: eDIA.ExperimentConfig
  langs:
  - csharp
  - vb
  name: experiment
  nameWithType: ExperimentConfig.experiment
  fullName: eDIA.ExperimentConfig.experiment
  type: Field
  source:
    id: experiment
    path: ''
    startLine: 6552
  assemblies:
  - cs.temp.dll
  namespace: eDIA
  syntax:
    content: public string experiment
    return:
      type: System.String
    content.vb: Public experiment As String
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: eDIA.ExperimentConfig.experimenter
  commentId: F:eDIA.ExperimentConfig.experimenter
  id: experimenter
  parent: eDIA.ExperimentConfig
  langs:
  - csharp
  - vb
  name: experimenter
  nameWithType: ExperimentConfig.experimenter
  fullName: eDIA.ExperimentConfig.experimenter
  type: Field
  source:
    id: experimenter
    path: ''
    startLine: 6553
  assemblies:
  - cs.temp.dll
  namespace: eDIA
  syntax:
    content: public string experimenter
    return:
      type: System.String
    content.vb: Public experimenter As String
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: eDIA.ExperimentConfig.session_number
  commentId: F:eDIA.ExperimentConfig.session_number
  id: session_number
  parent: eDIA.ExperimentConfig
  langs:
  - csharp
  - vb
  name: session_number
  nameWithType: ExperimentConfig.session_number
  fullName: eDIA.ExperimentConfig.session_number
  type: Field
  source:
    id: session_number
    path: ''
    startLine: 6554
  assemblies:
  - cs.temp.dll
  namespace: eDIA
  syntax:
    content: public int session_number
    return:
      type: System.Int32
    content.vb: Public session_number As Integer
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: eDIA.ExperimentConfig.participant_details
  commentId: F:eDIA.ExperimentConfig.participant_details
  id: participant_details
  parent: eDIA.ExperimentConfig
  langs:
  - csharp
  - vb
  name: participant_details
  nameWithType: ExperimentConfig.participant_details
  fullName: eDIA.ExperimentConfig.participant_details
  type: Field
  source:
    id: participant_details
    path: ''
    startLine: 6555
  assemblies:
  - cs.temp.dll
  namespace: eDIA
  syntax:
    content: public List<SettingsTuple> participant_details
    return:
      type: System.Collections.Generic.List{eDIA.SettingsTuple}
    content.vb: Public participant_details As List(Of SettingsTuple)
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: eDIA.ExperimentConfig.isReady
  commentId: F:eDIA.ExperimentConfig.isReady
  id: isReady
  parent: eDIA.ExperimentConfig
  langs:
  - csharp
  - vb
  name: isReady
  nameWithType: ExperimentConfig.isReady
  fullName: eDIA.ExperimentConfig.isReady
  type: Field
  source:
    id: isReady
    path: ''
    startLine: 6558
  assemblies:
  - cs.temp.dll
  namespace: eDIA
  syntax:
    content: public bool isReady
    return:
      type: System.Boolean
    content.vb: Public isReady As Boolean
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: eDIA.ExperimentConfig.GetExperimentSummary
  commentId: M:eDIA.ExperimentConfig.GetExperimentSummary
  id: GetExperimentSummary
  parent: eDIA.ExperimentConfig
  langs:
  - csharp
  - vb
  name: GetExperimentSummary()
  nameWithType: ExperimentConfig.GetExperimentSummary()
  fullName: eDIA.ExperimentConfig.GetExperimentSummary()
  type: Method
  source:
    id: GetExperimentSummary
    path: ''
    startLine: 6561
  assemblies:
  - cs.temp.dll
  namespace: eDIA
  syntax:
    content: public string[] GetExperimentSummary()
    return:
      type: System.String[]
    content.vb: Public Function GetExperimentSummary As String()
  overload: eDIA.ExperimentConfig.GetExperimentSummary*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: eDIA.ExperimentConfig.GetParticipantID
  commentId: M:eDIA.ExperimentConfig.GetParticipantID
  id: GetParticipantID
  parent: eDIA.ExperimentConfig
  langs:
  - csharp
  - vb
  name: GetParticipantID()
  nameWithType: ExperimentConfig.GetParticipantID()
  fullName: eDIA.ExperimentConfig.GetParticipantID()
  type: Method
  source:
    id: GetParticipantID
    path: ''
    startLine: 6565
  assemblies:
  - cs.temp.dll
  namespace: eDIA
  syntax:
    content: public string GetParticipantID()
    return:
      type: System.String
    content.vb: Public Function GetParticipantID As String
  overload: eDIA.ExperimentConfig.GetParticipantID*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: eDIA.ExperimentConfig.GetParticipantDetailsAsDict
  commentId: M:eDIA.ExperimentConfig.GetParticipantDetailsAsDict
  id: GetParticipantDetailsAsDict
  parent: eDIA.ExperimentConfig
  langs:
  - csharp
  - vb
  name: GetParticipantDetailsAsDict()
  nameWithType: ExperimentConfig.GetParticipantDetailsAsDict()
  fullName: eDIA.ExperimentConfig.GetParticipantDetailsAsDict()
  type: Method
  source:
    id: GetParticipantDetailsAsDict
    path: ''
    startLine: 6569
  assemblies:
  - cs.temp.dll
  namespace: eDIA
  syntax:
    content: public Dictionary<string, object> GetParticipantDetailsAsDict()
    return:
      type: System.Collections.Generic.Dictionary{System.String,System.Object}
    content.vb: Public Function GetParticipantDetailsAsDict As Dictionary(Of String, Object)
  overload: eDIA.ExperimentConfig.GetParticipantDetailsAsDict*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: eDIA
  commentId: N:eDIA
  name: eDIA
  nameWithType: eDIA
  fullName: eDIA
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Int32
  commentId: T:System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.Collections.Generic.List{eDIA.SettingsTuple}
  commentId: T:System.Collections.Generic.List{eDIA.SettingsTuple}
  parent: System.Collections.Generic
  definition: System.Collections.Generic.List`1
  name: List<SettingsTuple>
  nameWithType: List<SettingsTuple>
  fullName: System.Collections.Generic.List<eDIA.SettingsTuple>
  nameWithType.vb: List(Of SettingsTuple)
  fullName.vb: System.Collections.Generic.List(Of eDIA.SettingsTuple)
  name.vb: List(Of SettingsTuple)
  spec.csharp:
  - uid: System.Collections.Generic.List`1
    name: List
    nameWithType: List
    fullName: System.Collections.Generic.List
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - uid: eDIA.SettingsTuple
    name: SettingsTuple
    nameWithType: SettingsTuple
    fullName: eDIA.SettingsTuple
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Collections.Generic.List`1
    name: List
    nameWithType: List
    fullName: System.Collections.Generic.List
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - uid: eDIA.SettingsTuple
    name: SettingsTuple
    nameWithType: SettingsTuple
    fullName: eDIA.SettingsTuple
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Collections.Generic.List`1
  commentId: T:System.Collections.Generic.List`1
  isExternal: true
  name: List<T>
  nameWithType: List<T>
  fullName: System.Collections.Generic.List<T>
  nameWithType.vb: List(Of T)
  fullName.vb: System.Collections.Generic.List(Of T)
  name.vb: List(Of T)
  spec.csharp:
  - uid: System.Collections.Generic.List`1
    name: List
    nameWithType: List
    fullName: System.Collections.Generic.List
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - name: T
    nameWithType: T
    fullName: T
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Collections.Generic.List`1
    name: List
    nameWithType: List
    fullName: System.Collections.Generic.List
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: T
    nameWithType: T
    fullName: T
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Collections.Generic
  commentId: N:System.Collections.Generic
  isExternal: true
  name: System.Collections.Generic
  nameWithType: System.Collections.Generic
  fullName: System.Collections.Generic
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: eDIA.ExperimentConfig.GetExperimentSummary*
  commentId: Overload:eDIA.ExperimentConfig.GetExperimentSummary
  name: GetExperimentSummary
  nameWithType: ExperimentConfig.GetExperimentSummary
  fullName: eDIA.ExperimentConfig.GetExperimentSummary
- uid: System.String[]
  isExternal: true
  name: String[]
  nameWithType: String[]
  fullName: System.String[]
  nameWithType.vb: String()
  fullName.vb: System.String()
  name.vb: String()
  spec.csharp:
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: '[]'
    nameWithType: '[]'
    fullName: '[]'
  spec.vb:
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: ()
    nameWithType: ()
    fullName: ()
- uid: eDIA.ExperimentConfig.GetParticipantID*
  commentId: Overload:eDIA.ExperimentConfig.GetParticipantID
  name: GetParticipantID
  nameWithType: ExperimentConfig.GetParticipantID
  fullName: eDIA.ExperimentConfig.GetParticipantID
- uid: eDIA.ExperimentConfig.GetParticipantDetailsAsDict*
  commentId: Overload:eDIA.ExperimentConfig.GetParticipantDetailsAsDict
  name: GetParticipantDetailsAsDict
  nameWithType: ExperimentConfig.GetParticipantDetailsAsDict
  fullName: eDIA.ExperimentConfig.GetParticipantDetailsAsDict
- uid: System.Collections.Generic.Dictionary{System.String,System.Object}
  commentId: T:System.Collections.Generic.Dictionary{System.String,System.Object}
  parent: System.Collections.Generic
  definition: System.Collections.Generic.Dictionary`2
  name: Dictionary<String, Object>
  nameWithType: Dictionary<String, Object>
  fullName: System.Collections.Generic.Dictionary<System.String, System.Object>
  nameWithType.vb: Dictionary(Of String, Object)
  fullName.vb: System.Collections.Generic.Dictionary(Of System.String, System.Object)
  name.vb: Dictionary(Of String, Object)
  spec.csharp:
  - uid: System.Collections.Generic.Dictionary`2
    name: Dictionary
    nameWithType: Dictionary
    fullName: System.Collections.Generic.Dictionary
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Collections.Generic.Dictionary`2
    name: Dictionary
    nameWithType: Dictionary
    fullName: System.Collections.Generic.Dictionary
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Collections.Generic.Dictionary`2
  commentId: T:System.Collections.Generic.Dictionary`2
  isExternal: true
  name: Dictionary<TKey, TValue>
  nameWithType: Dictionary<TKey, TValue>
  fullName: System.Collections.Generic.Dictionary<TKey, TValue>
  nameWithType.vb: Dictionary(Of TKey, TValue)
  fullName.vb: System.Collections.Generic.Dictionary(Of TKey, TValue)
  name.vb: Dictionary(Of TKey, TValue)
  spec.csharp:
  - uid: System.Collections.Generic.Dictionary`2
    name: Dictionary
    nameWithType: Dictionary
    fullName: System.Collections.Generic.Dictionary
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - name: TKey
    nameWithType: TKey
    fullName: TKey
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: TValue
    nameWithType: TValue
    fullName: TValue
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Collections.Generic.Dictionary`2
    name: Dictionary
    nameWithType: Dictionary
    fullName: System.Collections.Generic.Dictionary
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: TKey
    nameWithType: TKey
    fullName: TKey
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: TValue
    nameWithType: TValue
    fullName: TValue
  - name: )
    nameWithType: )
    fullName: )
