### YamlMime:ManagedReference
items:
- uid: eDIA.PanelConfigSelection
  commentId: T:eDIA.PanelConfigSelection
  id: PanelConfigSelection
  parent: eDIA
  children:
  - eDIA.PanelConfigSelection.btnSubmit
  - eDIA.PanelConfigSelection.BtnSubmitPressed
  - eDIA.PanelConfigSelection.configFilesOptions
  - eDIA.PanelConfigSelection.infoTextField
  - eDIA.PanelConfigSelection.UpdateParticipantConfigList
  langs:
  - csharp
  - vb
  name: PanelConfigSelection
  nameWithType: PanelConfigSelection
  fullName: eDIA.PanelConfigSelection
  type: Class
  source:
    id: PanelConfigSelection
    path: ''
    startLine: 9130
  assemblies:
  - cs.temp.dll
  namespace: eDIA
  summary: GUI element that enables the user to choose from a dropdown of found experiment config files
  example: []
  syntax:
    content: 'public class PanelConfigSelection : ExperimenterPanel'
    content.vb: >-
      Public Class PanelConfigSelection
          Inherits ExperimenterPanel
  inheritance:
  - System.Object
  - eDIA.ExperimenterPanel
  inheritedMembers:
  - eDIA.ExperimenterPanel.children
  - eDIA.ExperimenterPanel.Awake
  - eDIA.ExperimenterPanel.ShowPanel
  - eDIA.ExperimenterPanel.HidePanel
  - eDIA.ExperimenterPanel.ApplyTheme
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: eDIA.PanelConfigSelection.configFilesOptions
  commentId: F:eDIA.PanelConfigSelection.configFilesOptions
  id: configFilesOptions
  parent: eDIA.PanelConfigSelection
  langs:
  - csharp
  - vb
  name: configFilesOptions
  nameWithType: PanelConfigSelection.configFilesOptions
  fullName: eDIA.PanelConfigSelection.configFilesOptions
  type: Field
  source:
    id: configFilesOptions
    path: ''
    startLine: 9133
  assemblies:
  - cs.temp.dll
  namespace: eDIA
  syntax:
    content: public TMP_Dropdown configFilesOptions
    return:
      type: Global.TMP_Dropdown
    content.vb: Public configFilesOptions As TMP_Dropdown
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: eDIA.PanelConfigSelection.btnSubmit
  commentId: F:eDIA.PanelConfigSelection.btnSubmit
  id: btnSubmit
  parent: eDIA.PanelConfigSelection
  langs:
  - csharp
  - vb
  name: btnSubmit
  nameWithType: PanelConfigSelection.btnSubmit
  fullName: eDIA.PanelConfigSelection.btnSubmit
  type: Field
  source:
    id: btnSubmit
    path: ''
    startLine: 9134
  assemblies:
  - cs.temp.dll
  namespace: eDIA
  syntax:
    content: public Button btnSubmit
    return:
      type: Global.Button
    content.vb: Public btnSubmit As Button
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: eDIA.PanelConfigSelection.infoTextField
  commentId: F:eDIA.PanelConfigSelection.infoTextField
  id: infoTextField
  parent: eDIA.PanelConfigSelection
  langs:
  - csharp
  - vb
  name: infoTextField
  nameWithType: PanelConfigSelection.infoTextField
  fullName: eDIA.PanelConfigSelection.infoTextField
  type: Field
  source:
    id: infoTextField
    path: ''
    startLine: 9135
  assemblies:
  - cs.temp.dll
  namespace: eDIA
  syntax:
    content: public TextMeshProUGUI infoTextField
    return:
      type: Global.TextMeshProUGUI
    content.vb: Public infoTextField As TextMeshProUGUI
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: eDIA.PanelConfigSelection.UpdateParticipantConfigList
  commentId: M:eDIA.PanelConfigSelection.UpdateParticipantConfigList
  id: UpdateParticipantConfigList
  parent: eDIA.PanelConfigSelection
  langs:
  - csharp
  - vb
  name: UpdateParticipantConfigList()
  nameWithType: PanelConfigSelection.UpdateParticipantConfigList()
  fullName: eDIA.PanelConfigSelection.UpdateParticipantConfigList()
  type: Method
  source:
    id: UpdateParticipantConfigList
    path: ''
    startLine: 9160
  assemblies:
  - cs.temp.dll
  namespace: eDIA
  summary: Update the participants list of selected task.
  example: []
  syntax:
    content: public void UpdateParticipantConfigList()
    content.vb: Public Sub UpdateParticipantConfigList
  overload: eDIA.PanelConfigSelection.UpdateParticipantConfigList*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: eDIA.PanelConfigSelection.BtnSubmitPressed
  commentId: M:eDIA.PanelConfigSelection.BtnSubmitPressed
  id: BtnSubmitPressed
  parent: eDIA.PanelConfigSelection
  langs:
  - csharp
  - vb
  name: BtnSubmitPressed()
  nameWithType: PanelConfigSelection.BtnSubmitPressed()
  fullName: eDIA.PanelConfigSelection.BtnSubmitPressed()
  type: Method
  source:
    id: BtnSubmitPressed
    path: ''
    startLine: 9197
  assemblies:
  - cs.temp.dll
  namespace: eDIA
  syntax:
    content: public void BtnSubmitPressed()
    content.vb: Public Sub BtnSubmitPressed
  overload: eDIA.PanelConfigSelection.BtnSubmitPressed*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: eDIA
  commentId: N:eDIA
  name: eDIA
  nameWithType: eDIA
  fullName: eDIA
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: eDIA.ExperimenterPanel
  commentId: T:eDIA.ExperimenterPanel
  parent: eDIA
  name: ExperimenterPanel
  nameWithType: ExperimenterPanel
  fullName: eDIA.ExperimenterPanel
- uid: eDIA.ExperimenterPanel.children
  commentId: F:eDIA.ExperimenterPanel.children
  parent: eDIA.ExperimenterPanel
  name: children
  nameWithType: ExperimenterPanel.children
  fullName: eDIA.ExperimenterPanel.children
- uid: eDIA.ExperimenterPanel.Awake
  commentId: M:eDIA.ExperimenterPanel.Awake
  parent: eDIA.ExperimenterPanel
  name: Awake()
  nameWithType: ExperimenterPanel.Awake()
  fullName: eDIA.ExperimenterPanel.Awake()
  spec.csharp:
  - uid: eDIA.ExperimenterPanel.Awake
    name: Awake
    nameWithType: ExperimenterPanel.Awake
    fullName: eDIA.ExperimenterPanel.Awake
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: eDIA.ExperimenterPanel.Awake
    name: Awake
    nameWithType: ExperimenterPanel.Awake
    fullName: eDIA.ExperimenterPanel.Awake
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: eDIA.ExperimenterPanel.ShowPanel
  commentId: M:eDIA.ExperimenterPanel.ShowPanel
  parent: eDIA.ExperimenterPanel
  name: ShowPanel()
  nameWithType: ExperimenterPanel.ShowPanel()
  fullName: eDIA.ExperimenterPanel.ShowPanel()
  spec.csharp:
  - uid: eDIA.ExperimenterPanel.ShowPanel
    name: ShowPanel
    nameWithType: ExperimenterPanel.ShowPanel
    fullName: eDIA.ExperimenterPanel.ShowPanel
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: eDIA.ExperimenterPanel.ShowPanel
    name: ShowPanel
    nameWithType: ExperimenterPanel.ShowPanel
    fullName: eDIA.ExperimenterPanel.ShowPanel
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: eDIA.ExperimenterPanel.HidePanel
  commentId: M:eDIA.ExperimenterPanel.HidePanel
  parent: eDIA.ExperimenterPanel
  name: HidePanel()
  nameWithType: ExperimenterPanel.HidePanel()
  fullName: eDIA.ExperimenterPanel.HidePanel()
  spec.csharp:
  - uid: eDIA.ExperimenterPanel.HidePanel
    name: HidePanel
    nameWithType: ExperimenterPanel.HidePanel
    fullName: eDIA.ExperimenterPanel.HidePanel
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: eDIA.ExperimenterPanel.HidePanel
    name: HidePanel
    nameWithType: ExperimenterPanel.HidePanel
    fullName: eDIA.ExperimenterPanel.HidePanel
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: eDIA.ExperimenterPanel.ApplyTheme
  commentId: M:eDIA.ExperimenterPanel.ApplyTheme
  parent: eDIA.ExperimenterPanel
  name: ApplyTheme()
  nameWithType: ExperimenterPanel.ApplyTheme()
  fullName: eDIA.ExperimenterPanel.ApplyTheme()
  spec.csharp:
  - uid: eDIA.ExperimenterPanel.ApplyTheme
    name: ApplyTheme
    nameWithType: ExperimenterPanel.ApplyTheme
    fullName: eDIA.ExperimenterPanel.ApplyTheme
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: eDIA.ExperimenterPanel.ApplyTheme
    name: ApplyTheme
    nameWithType: ExperimenterPanel.ApplyTheme
    fullName: eDIA.ExperimenterPanel.ApplyTheme
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: Global.TMP_Dropdown
  isExternal: true
  name: TMP_Dropdown
  nameWithType: TMP_Dropdown
  fullName: TMP_Dropdown
- uid: Global.Button
  isExternal: true
  name: Button
  nameWithType: Button
  fullName: Button
- uid: Global.TextMeshProUGUI
  isExternal: true
  name: TextMeshProUGUI
  nameWithType: TextMeshProUGUI
  fullName: TextMeshProUGUI
- uid: eDIA.PanelConfigSelection.UpdateParticipantConfigList*
  commentId: Overload:eDIA.PanelConfigSelection.UpdateParticipantConfigList
  name: UpdateParticipantConfigList
  nameWithType: PanelConfigSelection.UpdateParticipantConfigList
  fullName: eDIA.PanelConfigSelection.UpdateParticipantConfigList
- uid: eDIA.PanelConfigSelection.BtnSubmitPressed*
  commentId: Overload:eDIA.PanelConfigSelection.BtnSubmitPressed
  name: BtnSubmitPressed
  nameWithType: PanelConfigSelection.BtnSubmitPressed
  fullName: eDIA.PanelConfigSelection.BtnSubmitPressed
