### YamlMime:ManagedReference
items:
- uid: eDIA.PanelApplicationSettings
  commentId: T:eDIA.PanelApplicationSettings
  id: PanelApplicationSettings
  parent: eDIA
  children:
  - eDIA.PanelApplicationSettings.Awake
  - eDIA.PanelApplicationSettings.btnApply
  - eDIA.PanelApplicationSettings.btnBrowse
  - eDIA.PanelApplicationSettings.btnClose
  - eDIA.PanelApplicationSettings.interactiveInteractorDropdown
  - eDIA.PanelApplicationSettings.languageDropdown
  - eDIA.PanelApplicationSettings.localSystemSettingsContainer
  - eDIA.PanelApplicationSettings.pathToLogfilesField
  - eDIA.PanelApplicationSettings.resolutionDropdown
  - eDIA.PanelApplicationSettings.ValueChanged
  - eDIA.PanelApplicationSettings.visibleInteractorDropdown
  - eDIA.PanelApplicationSettings.volumeSlider
  langs:
  - csharp
  - vb
  name: PanelApplicationSettings
  nameWithType: PanelApplicationSettings
  fullName: eDIA.PanelApplicationSettings
  type: Class
  source:
    id: PanelApplicationSettings
    path: ''
    startLine: 9012
  assemblies:
  - cs.temp.dll
  namespace: eDIA
  syntax:
    content: 'public class PanelApplicationSettings : ExperimenterPanel'
    content.vb: >-
      Public Class PanelApplicationSettings
          Inherits ExperimenterPanel
  inheritance:
  - System.Object
  - eDIA.ExperimenterPanel
  inheritedMembers:
  - eDIA.ExperimenterPanel.children
  - eDIA.ExperimenterPanel.ShowPanel
  - eDIA.ExperimenterPanel.HidePanel
  - eDIA.ExperimenterPanel.ApplyTheme
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: eDIA.PanelApplicationSettings.btnApply
  commentId: F:eDIA.PanelApplicationSettings.btnApply
  id: btnApply
  parent: eDIA.PanelApplicationSettings
  langs:
  - csharp
  - vb
  name: btnApply
  nameWithType: PanelApplicationSettings.btnApply
  fullName: eDIA.PanelApplicationSettings.btnApply
  type: Field
  source:
    id: btnApply
    path: ''
    startLine: 9016
  assemblies:
  - cs.temp.dll
  namespace: eDIA
  syntax:
    content: public Button btnApply
    return:
      type: Global.Button
    content.vb: Public btnApply As Button
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: eDIA.PanelApplicationSettings.btnClose
  commentId: F:eDIA.PanelApplicationSettings.btnClose
  id: btnClose
  parent: eDIA.PanelApplicationSettings
  langs:
  - csharp
  - vb
  name: btnClose
  nameWithType: PanelApplicationSettings.btnClose
  fullName: eDIA.PanelApplicationSettings.btnClose
  type: Field
  source:
    id: btnClose
    path: ''
    startLine: 9017
  assemblies:
  - cs.temp.dll
  namespace: eDIA
  syntax:
    content: public Button btnClose
    return:
      type: Global.Button
    content.vb: Public btnClose As Button
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: eDIA.PanelApplicationSettings.btnBrowse
  commentId: F:eDIA.PanelApplicationSettings.btnBrowse
  id: btnBrowse
  parent: eDIA.PanelApplicationSettings
  langs:
  - csharp
  - vb
  name: btnBrowse
  nameWithType: PanelApplicationSettings.btnBrowse
  fullName: eDIA.PanelApplicationSettings.btnBrowse
  type: Field
  source:
    id: btnBrowse
    path: ''
    startLine: 9018
  assemblies:
  - cs.temp.dll
  namespace: eDIA
  syntax:
    content: public Button btnBrowse
    return:
      type: Global.Button
    content.vb: Public btnBrowse As Button
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: eDIA.PanelApplicationSettings.volumeSlider
  commentId: F:eDIA.PanelApplicationSettings.volumeSlider
  id: volumeSlider
  parent: eDIA.PanelApplicationSettings
  langs:
  - csharp
  - vb
  name: volumeSlider
  nameWithType: PanelApplicationSettings.volumeSlider
  fullName: eDIA.PanelApplicationSettings.volumeSlider
  type: Field
  source:
    id: volumeSlider
    path: ''
    startLine: 9021
  assemblies:
  - cs.temp.dll
  namespace: eDIA
  syntax:
    content: public Slider volumeSlider
    return:
      type: Global.Slider
    content.vb: Public volumeSlider As Slider
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: eDIA.PanelApplicationSettings.resolutionDropdown
  commentId: F:eDIA.PanelApplicationSettings.resolutionDropdown
  id: resolutionDropdown
  parent: eDIA.PanelApplicationSettings
  langs:
  - csharp
  - vb
  name: resolutionDropdown
  nameWithType: PanelApplicationSettings.resolutionDropdown
  fullName: eDIA.PanelApplicationSettings.resolutionDropdown
  type: Field
  source:
    id: resolutionDropdown
    path: ''
    startLine: 9022
  assemblies:
  - cs.temp.dll
  namespace: eDIA
  syntax:
    content: public TMP_Dropdown resolutionDropdown
    return:
      type: Global.TMP_Dropdown
    content.vb: Public resolutionDropdown As TMP_Dropdown
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: eDIA.PanelApplicationSettings.interactiveInteractorDropdown
  commentId: F:eDIA.PanelApplicationSettings.interactiveInteractorDropdown
  id: interactiveInteractorDropdown
  parent: eDIA.PanelApplicationSettings
  langs:
  - csharp
  - vb
  name: interactiveInteractorDropdown
  nameWithType: PanelApplicationSettings.interactiveInteractorDropdown
  fullName: eDIA.PanelApplicationSettings.interactiveInteractorDropdown
  type: Field
  source:
    id: interactiveInteractorDropdown
    path: ''
    startLine: 9023
  assemblies:
  - cs.temp.dll
  namespace: eDIA
  syntax:
    content: public TMP_Dropdown interactiveInteractorDropdown
    return:
      type: Global.TMP_Dropdown
    content.vb: Public interactiveInteractorDropdown As TMP_Dropdown
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: eDIA.PanelApplicationSettings.visibleInteractorDropdown
  commentId: F:eDIA.PanelApplicationSettings.visibleInteractorDropdown
  id: visibleInteractorDropdown
  parent: eDIA.PanelApplicationSettings
  langs:
  - csharp
  - vb
  name: visibleInteractorDropdown
  nameWithType: PanelApplicationSettings.visibleInteractorDropdown
  fullName: eDIA.PanelApplicationSettings.visibleInteractorDropdown
  type: Field
  source:
    id: visibleInteractorDropdown
    path: ''
    startLine: 9024
  assemblies:
  - cs.temp.dll
  namespace: eDIA
  syntax:
    content: public TMP_Dropdown visibleInteractorDropdown
    return:
      type: Global.TMP_Dropdown
    content.vb: Public visibleInteractorDropdown As TMP_Dropdown
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: eDIA.PanelApplicationSettings.languageDropdown
  commentId: F:eDIA.PanelApplicationSettings.languageDropdown
  id: languageDropdown
  parent: eDIA.PanelApplicationSettings
  langs:
  - csharp
  - vb
  name: languageDropdown
  nameWithType: PanelApplicationSettings.languageDropdown
  fullName: eDIA.PanelApplicationSettings.languageDropdown
  type: Field
  source:
    id: languageDropdown
    path: ''
    startLine: 9025
  assemblies:
  - cs.temp.dll
  namespace: eDIA
  syntax:
    content: public TMP_Dropdown languageDropdown
    return:
      type: Global.TMP_Dropdown
    content.vb: Public languageDropdown As TMP_Dropdown
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: eDIA.PanelApplicationSettings.pathToLogfilesField
  commentId: F:eDIA.PanelApplicationSettings.pathToLogfilesField
  id: pathToLogfilesField
  parent: eDIA.PanelApplicationSettings
  langs:
  - csharp
  - vb
  name: pathToLogfilesField
  nameWithType: PanelApplicationSettings.pathToLogfilesField
  fullName: eDIA.PanelApplicationSettings.pathToLogfilesField
  type: Field
  source:
    id: pathToLogfilesField
    path: ''
    startLine: 9026
  assemblies:
  - cs.temp.dll
  namespace: eDIA
  syntax:
    content: public TextMeshProUGUI pathToLogfilesField
    return:
      type: Global.TextMeshProUGUI
    content.vb: Public pathToLogfilesField As TextMeshProUGUI
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: eDIA.PanelApplicationSettings.localSystemSettingsContainer
  commentId: F:eDIA.PanelApplicationSettings.localSystemSettingsContainer
  id: localSystemSettingsContainer
  parent: eDIA.PanelApplicationSettings
  langs:
  - csharp
  - vb
  name: localSystemSettingsContainer
  nameWithType: PanelApplicationSettings.localSystemSettingsContainer
  fullName: eDIA.PanelApplicationSettings.localSystemSettingsContainer
  type: Field
  source:
    id: localSystemSettingsContainer
    path: ''
    startLine: 9028
  assemblies:
  - cs.temp.dll
  namespace: eDIA
  syntax:
    content: public SettingsDeclaration localSystemSettingsContainer
    return:
      type: eDIA.SettingsDeclaration
    content.vb: Public localSystemSettingsContainer As SettingsDeclaration
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: eDIA.PanelApplicationSettings.Awake
  commentId: M:eDIA.PanelApplicationSettings.Awake
  id: Awake
  parent: eDIA.PanelApplicationSettings
  langs:
  - csharp
  - vb
  name: Awake()
  nameWithType: PanelApplicationSettings.Awake()
  fullName: eDIA.PanelApplicationSettings.Awake()
  type: Method
  source:
    id: Awake
    path: ''
    startLine: 9031
  assemblies:
  - cs.temp.dll
  namespace: eDIA
  syntax:
    content: public override void Awake()
    content.vb: Public Overrides Sub Awake
  overridden: eDIA.ExperimenterPanel.Awake
  overload: eDIA.PanelApplicationSettings.Awake*
  modifiers.csharp:
  - public
  - override
  modifiers.vb:
  - Public
  - Overrides
- uid: eDIA.PanelApplicationSettings.ValueChanged
  commentId: M:eDIA.PanelApplicationSettings.ValueChanged
  id: ValueChanged
  parent: eDIA.PanelApplicationSettings
  langs:
  - csharp
  - vb
  name: ValueChanged()
  nameWithType: PanelApplicationSettings.ValueChanged()
  fullName: eDIA.PanelApplicationSettings.ValueChanged()
  type: Method
  source:
    id: ValueChanged
    path: ''
    startLine: 9066
  assemblies:
  - cs.temp.dll
  namespace: eDIA
  syntax:
    content: public void ValueChanged()
    content.vb: Public Sub ValueChanged
  overload: eDIA.PanelApplicationSettings.ValueChanged*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: eDIA
  commentId: N:eDIA
  name: eDIA
  nameWithType: eDIA
  fullName: eDIA
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: eDIA.ExperimenterPanel
  commentId: T:eDIA.ExperimenterPanel
  parent: eDIA
  name: ExperimenterPanel
  nameWithType: ExperimenterPanel
  fullName: eDIA.ExperimenterPanel
- uid: eDIA.ExperimenterPanel.children
  commentId: F:eDIA.ExperimenterPanel.children
  parent: eDIA.ExperimenterPanel
  name: children
  nameWithType: ExperimenterPanel.children
  fullName: eDIA.ExperimenterPanel.children
- uid: eDIA.ExperimenterPanel.ShowPanel
  commentId: M:eDIA.ExperimenterPanel.ShowPanel
  parent: eDIA.ExperimenterPanel
  name: ShowPanel()
  nameWithType: ExperimenterPanel.ShowPanel()
  fullName: eDIA.ExperimenterPanel.ShowPanel()
  spec.csharp:
  - uid: eDIA.ExperimenterPanel.ShowPanel
    name: ShowPanel
    nameWithType: ExperimenterPanel.ShowPanel
    fullName: eDIA.ExperimenterPanel.ShowPanel
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: eDIA.ExperimenterPanel.ShowPanel
    name: ShowPanel
    nameWithType: ExperimenterPanel.ShowPanel
    fullName: eDIA.ExperimenterPanel.ShowPanel
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: eDIA.ExperimenterPanel.HidePanel
  commentId: M:eDIA.ExperimenterPanel.HidePanel
  parent: eDIA.ExperimenterPanel
  name: HidePanel()
  nameWithType: ExperimenterPanel.HidePanel()
  fullName: eDIA.ExperimenterPanel.HidePanel()
  spec.csharp:
  - uid: eDIA.ExperimenterPanel.HidePanel
    name: HidePanel
    nameWithType: ExperimenterPanel.HidePanel
    fullName: eDIA.ExperimenterPanel.HidePanel
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: eDIA.ExperimenterPanel.HidePanel
    name: HidePanel
    nameWithType: ExperimenterPanel.HidePanel
    fullName: eDIA.ExperimenterPanel.HidePanel
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: eDIA.ExperimenterPanel.ApplyTheme
  commentId: M:eDIA.ExperimenterPanel.ApplyTheme
  parent: eDIA.ExperimenterPanel
  name: ApplyTheme()
  nameWithType: ExperimenterPanel.ApplyTheme()
  fullName: eDIA.ExperimenterPanel.ApplyTheme()
  spec.csharp:
  - uid: eDIA.ExperimenterPanel.ApplyTheme
    name: ApplyTheme
    nameWithType: ExperimenterPanel.ApplyTheme
    fullName: eDIA.ExperimenterPanel.ApplyTheme
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: eDIA.ExperimenterPanel.ApplyTheme
    name: ApplyTheme
    nameWithType: ExperimenterPanel.ApplyTheme
    fullName: eDIA.ExperimenterPanel.ApplyTheme
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: Global.Button
  isExternal: true
  name: Button
  nameWithType: Button
  fullName: Button
- uid: Global.Slider
  commentId: '!:Global.Slider'
  isExternal: true
  name: Slider
  nameWithType: Slider
  fullName: Slider
- uid: Global.TMP_Dropdown
  isExternal: true
  name: TMP_Dropdown
  nameWithType: TMP_Dropdown
  fullName: TMP_Dropdown
- uid: Global.TextMeshProUGUI
  isExternal: true
  name: TextMeshProUGUI
  nameWithType: TextMeshProUGUI
  fullName: TextMeshProUGUI
- uid: eDIA.SettingsDeclaration
  commentId: T:eDIA.SettingsDeclaration
  parent: eDIA
  name: SettingsDeclaration
  nameWithType: SettingsDeclaration
  fullName: eDIA.SettingsDeclaration
- uid: eDIA.ExperimenterPanel.Awake
  commentId: M:eDIA.ExperimenterPanel.Awake
  parent: eDIA.ExperimenterPanel
  name: Awake()
  nameWithType: ExperimenterPanel.Awake()
  fullName: eDIA.ExperimenterPanel.Awake()
  spec.csharp:
  - uid: eDIA.ExperimenterPanel.Awake
    name: Awake
    nameWithType: ExperimenterPanel.Awake
    fullName: eDIA.ExperimenterPanel.Awake
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: eDIA.ExperimenterPanel.Awake
    name: Awake
    nameWithType: ExperimenterPanel.Awake
    fullName: eDIA.ExperimenterPanel.Awake
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: eDIA.PanelApplicationSettings.Awake*
  commentId: Overload:eDIA.PanelApplicationSettings.Awake
  name: Awake
  nameWithType: PanelApplicationSettings.Awake
  fullName: eDIA.PanelApplicationSettings.Awake
- uid: eDIA.PanelApplicationSettings.ValueChanged*
  commentId: Overload:eDIA.PanelApplicationSettings.ValueChanged
  name: ValueChanged
  nameWithType: PanelApplicationSettings.ValueChanged
  fullName: eDIA.PanelApplicationSettings.ValueChanged
