### YamlMime:ManagedReference
items:
- uid: eDIA.TrialSettings
  commentId: T:eDIA.TrialSettings
  id: TrialSettings
  parent: eDIA
  children:
  - eDIA.TrialSettings.keys
  - eDIA.TrialSettings.valueList
  langs:
  - csharp
  - vb
  name: TrialSettings
  nameWithType: TrialSettings
  fullName: eDIA.TrialSettings
  type: Class
  source:
    id: TrialSettings
    path: ''
    startLine: 6531
  assemblies:
  - cs.temp.dll
  namespace: eDIA
  summary: Experiment trial settings container
  example: []
  syntax:
    content: >-
      [Serializable]

      public class TrialSettings
    content.vb: >-
      <Serializable>

      Public Class TrialSettings
  inheritance:
  - System.Object
  attributes:
  - type: System.SerializableAttribute
    ctor: System.SerializableAttribute.#ctor
    arguments: []
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: eDIA.TrialSettings.keys
  commentId: F:eDIA.TrialSettings.keys
  id: keys
  parent: eDIA.TrialSettings
  langs:
  - csharp
  - vb
  name: keys
  nameWithType: TrialSettings.keys
  fullName: eDIA.TrialSettings.keys
  type: Field
  source:
    id: keys
    path: ''
    startLine: 6534
  assemblies:
  - cs.temp.dll
  namespace: eDIA
  syntax:
    content: public List<string> keys
    return:
      type: System.Collections.Generic.List{System.String}
    content.vb: Public keys As List(Of String)
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: eDIA.TrialSettings.valueList
  commentId: F:eDIA.TrialSettings.valueList
  id: valueList
  parent: eDIA.TrialSettings
  langs:
  - csharp
  - vb
  name: valueList
  nameWithType: TrialSettings.valueList
  fullName: eDIA.TrialSettings.valueList
  type: Field
  source:
    id: valueList
    path: ''
    startLine: 6535
  assemblies:
  - cs.temp.dll
  namespace: eDIA
  syntax:
    content: public List<ValueList> valueList
    return:
      type: System.Collections.Generic.List{eDIA.ValueList}
    content.vb: Public valueList As List(Of ValueList)
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: eDIA
  commentId: N:eDIA
  name: eDIA
  nameWithType: eDIA
  fullName: eDIA
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: System.Collections.Generic.List{System.String}
  commentId: T:System.Collections.Generic.List{System.String}
  parent: System.Collections.Generic
  definition: System.Collections.Generic.List`1
  name: List<String>
  nameWithType: List<String>
  fullName: System.Collections.Generic.List<System.String>
  nameWithType.vb: List(Of String)
  fullName.vb: System.Collections.Generic.List(Of System.String)
  name.vb: List(Of String)
  spec.csharp:
  - uid: System.Collections.Generic.List`1
    name: List
    nameWithType: List
    fullName: System.Collections.Generic.List
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Collections.Generic.List`1
    name: List
    nameWithType: List
    fullName: System.Collections.Generic.List
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Collections.Generic.List`1
  commentId: T:System.Collections.Generic.List`1
  isExternal: true
  name: List<T>
  nameWithType: List<T>
  fullName: System.Collections.Generic.List<T>
  nameWithType.vb: List(Of T)
  fullName.vb: System.Collections.Generic.List(Of T)
  name.vb: List(Of T)
  spec.csharp:
  - uid: System.Collections.Generic.List`1
    name: List
    nameWithType: List
    fullName: System.Collections.Generic.List
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - name: T
    nameWithType: T
    fullName: T
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Collections.Generic.List`1
    name: List
    nameWithType: List
    fullName: System.Collections.Generic.List
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: T
    nameWithType: T
    fullName: T
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Collections.Generic
  commentId: N:System.Collections.Generic
  isExternal: true
  name: System.Collections.Generic
  nameWithType: System.Collections.Generic
  fullName: System.Collections.Generic
- uid: System.Collections.Generic.List{eDIA.ValueList}
  commentId: T:System.Collections.Generic.List{eDIA.ValueList}
  parent: System.Collections.Generic
  definition: System.Collections.Generic.List`1
  name: List<ValueList>
  nameWithType: List<ValueList>
  fullName: System.Collections.Generic.List<eDIA.ValueList>
  nameWithType.vb: List(Of ValueList)
  fullName.vb: System.Collections.Generic.List(Of eDIA.ValueList)
  name.vb: List(Of ValueList)
  spec.csharp:
  - uid: System.Collections.Generic.List`1
    name: List
    nameWithType: List
    fullName: System.Collections.Generic.List
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - uid: eDIA.ValueList
    name: ValueList
    nameWithType: ValueList
    fullName: eDIA.ValueList
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Collections.Generic.List`1
    name: List
    nameWithType: List
    fullName: System.Collections.Generic.List
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - uid: eDIA.ValueList
    name: ValueList
    nameWithType: ValueList
    fullName: eDIA.ValueList
  - name: )
    nameWithType: )
    fullName: )
