### YamlMime:ManagedReference
items:
- uid: eDIA.ExperimentManager.ExperimentConfig
  commentId: T:eDIA.ExperimentManager.ExperimentConfig
  id: ExperimentManager.ExperimentConfig
  parent: eDIA
  children:
  - eDIA.ExperimentManager.ExperimentConfig.blockInstructions
  - eDIA.ExperimentManager.ExperimentConfig.breakAfter
  - eDIA.ExperimentManager.ExperimentConfig.experiment
  - eDIA.ExperimentManager.ExperimentConfig.experimenter
  - eDIA.ExperimentManager.ExperimentConfig.GetBlockIntroduction(System.Int32)
  - eDIA.ExperimentManager.ExperimentConfig.hasBlockIntroduction(System.Int32)
  - eDIA.ExperimentManager.ExperimentConfig.participantID
  - eDIA.ExperimentManager.ExperimentConfig.participantInfo
  - eDIA.ExperimentManager.ExperimentConfig.sessionNumber
  - eDIA.ExperimentManager.ExperimentConfig.sessionSettings
  - eDIA.ExperimentManager.ExperimentConfig.trialSequenceKeys
  - eDIA.ExperimentManager.ExperimentConfig.trialSequenceValues
  langs:
  - csharp
  - vb
  name: ExperimentManager.ExperimentConfig
  nameWithType: ExperimentManager.ExperimentConfig
  fullName: eDIA.ExperimentManager.ExperimentConfig
  type: Class
  source:
    id: ExperimentConfig
    path: ''
    startLine: 505
  assemblies:
  - cs.temp.dll
  namespace: eDIA
  summary: 'Main container to store sessions config, either from disk, editor or network '
  example: []
  syntax:
    content: >-
      [Serializable]

      public class ExperimentConfig
    content.vb: >-
      <Serializable>

      Public Class ExperimentConfig
  inheritance:
  - System.Object
  attributes:
  - type: System.SerializableAttribute
    ctor: System.SerializableAttribute.#ctor
    arguments: []
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: eDIA.ExperimentManager.ExperimentConfig.experiment
  commentId: F:eDIA.ExperimentManager.ExperimentConfig.experiment
  id: experiment
  parent: eDIA.ExperimentManager.ExperimentConfig
  langs:
  - csharp
  - vb
  name: experiment
  nameWithType: ExperimentManager.ExperimentConfig.experiment
  fullName: eDIA.ExperimentManager.ExperimentConfig.experiment
  type: Field
  source:
    id: experiment
    path: ''
    startLine: 507
  assemblies:
  - cs.temp.dll
  namespace: eDIA
  syntax:
    content: public string experiment
    return:
      type: System.String
    content.vb: Public experiment As String
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: eDIA.ExperimentManager.ExperimentConfig.experimenter
  commentId: F:eDIA.ExperimentManager.ExperimentConfig.experimenter
  id: experimenter
  parent: eDIA.ExperimentManager.ExperimentConfig
  langs:
  - csharp
  - vb
  name: experimenter
  nameWithType: ExperimentManager.ExperimentConfig.experimenter
  fullName: eDIA.ExperimentManager.ExperimentConfig.experimenter
  type: Field
  source:
    id: experimenter
    path: ''
    startLine: 508
  assemblies:
  - cs.temp.dll
  namespace: eDIA
  syntax:
    content: public string experimenter
    return:
      type: System.String
    content.vb: Public experimenter As String
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: eDIA.ExperimentManager.ExperimentConfig.participantID
  commentId: F:eDIA.ExperimentManager.ExperimentConfig.participantID
  id: participantID
  parent: eDIA.ExperimentManager.ExperimentConfig
  langs:
  - csharp
  - vb
  name: participantID
  nameWithType: ExperimentManager.ExperimentConfig.participantID
  fullName: eDIA.ExperimentManager.ExperimentConfig.participantID
  type: Field
  source:
    id: participantID
    path: ''
    startLine: 509
  assemblies:
  - cs.temp.dll
  namespace: eDIA
  syntax:
    content: public string participantID
    return:
      type: System.String
    content.vb: Public participantID As String
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: eDIA.ExperimentManager.ExperimentConfig.sessionNumber
  commentId: F:eDIA.ExperimentManager.ExperimentConfig.sessionNumber
  id: sessionNumber
  parent: eDIA.ExperimentManager.ExperimentConfig
  langs:
  - csharp
  - vb
  name: sessionNumber
  nameWithType: ExperimentManager.ExperimentConfig.sessionNumber
  fullName: eDIA.ExperimentManager.ExperimentConfig.sessionNumber
  type: Field
  source:
    id: sessionNumber
    path: ''
    startLine: 510
  assemblies:
  - cs.temp.dll
  namespace: eDIA
  syntax:
    content: public int sessionNumber
    return:
      type: System.Int32
    content.vb: Public sessionNumber As Integer
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: eDIA.ExperimentManager.ExperimentConfig.participantInfo
  commentId: F:eDIA.ExperimentManager.ExperimentConfig.participantInfo
  id: participantInfo
  parent: eDIA.ExperimentManager.ExperimentConfig
  langs:
  - csharp
  - vb
  name: participantInfo
  nameWithType: ExperimentManager.ExperimentConfig.participantInfo
  fullName: eDIA.ExperimentManager.ExperimentConfig.participantInfo
  type: Field
  source:
    id: participantInfo
    path: ''
    startLine: 511
  assemblies:
  - cs.temp.dll
  namespace: eDIA
  syntax:
    content: public List<ExperimentManager.SettingsTuple> participantInfo
    return:
      type: Global.List{eDIA.ExperimentManager.SettingsTuple}
    content.vb: Public participantInfo As List(Of ExperimentManager.SettingsTuple)
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: eDIA.ExperimentManager.ExperimentConfig.sessionSettings
  commentId: F:eDIA.ExperimentManager.ExperimentConfig.sessionSettings
  id: sessionSettings
  parent: eDIA.ExperimentManager.ExperimentConfig
  langs:
  - csharp
  - vb
  name: sessionSettings
  nameWithType: ExperimentManager.ExperimentConfig.sessionSettings
  fullName: eDIA.ExperimentManager.ExperimentConfig.sessionSettings
  type: Field
  source:
    id: sessionSettings
    path: ''
    startLine: 512
  assemblies:
  - cs.temp.dll
  namespace: eDIA
  syntax:
    content: public List<ExperimentManager.SettingsTuple> sessionSettings
    return:
      type: Global.List{eDIA.ExperimentManager.SettingsTuple}
    content.vb: Public sessionSettings As List(Of ExperimentManager.SettingsTuple)
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: eDIA.ExperimentManager.ExperimentConfig.blockInstructions
  commentId: F:eDIA.ExperimentManager.ExperimentConfig.blockInstructions
  id: blockInstructions
  parent: eDIA.ExperimentManager.ExperimentConfig
  langs:
  - csharp
  - vb
  name: blockInstructions
  nameWithType: ExperimentManager.ExperimentConfig.blockInstructions
  fullName: eDIA.ExperimentManager.ExperimentConfig.blockInstructions
  type: Field
  source:
    id: blockInstructions
    path: ''
    startLine: 513
  assemblies:
  - cs.temp.dll
  namespace: eDIA
  syntax:
    content: public List<ExperimentManager.SettingsTuple> blockInstructions
    return:
      type: Global.List{eDIA.ExperimentManager.SettingsTuple}
    content.vb: Public blockInstructions As List(Of ExperimentManager.SettingsTuple)
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: eDIA.ExperimentManager.ExperimentConfig.breakAfter
  commentId: F:eDIA.ExperimentManager.ExperimentConfig.breakAfter
  id: breakAfter
  parent: eDIA.ExperimentManager.ExperimentConfig
  langs:
  - csharp
  - vb
  name: breakAfter
  nameWithType: ExperimentManager.ExperimentConfig.breakAfter
  fullName: eDIA.ExperimentManager.ExperimentConfig.breakAfter
  type: Field
  source:
    id: breakAfter
    path: ''
    startLine: 514
  assemblies:
  - cs.temp.dll
  namespace: eDIA
  syntax:
    content: public List<int> breakAfter
    return:
      type: Global.List{System.Int32}
    content.vb: Public breakAfter As List(Of Integer)
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: eDIA.ExperimentManager.ExperimentConfig.trialSequenceKeys
  commentId: F:eDIA.ExperimentManager.ExperimentConfig.trialSequenceKeys
  id: trialSequenceKeys
  parent: eDIA.ExperimentManager.ExperimentConfig
  langs:
  - csharp
  - vb
  name: trialSequenceKeys
  nameWithType: ExperimentManager.ExperimentConfig.trialSequenceKeys
  fullName: eDIA.ExperimentManager.ExperimentConfig.trialSequenceKeys
  type: Field
  source:
    id: trialSequenceKeys
    path: ''
    startLine: 515
  assemblies:
  - cs.temp.dll
  namespace: eDIA
  syntax:
    content: public List<string> trialSequenceKeys
    return:
      type: Global.List{System.String}
    content.vb: Public trialSequenceKeys As List(Of String)
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: eDIA.ExperimentManager.ExperimentConfig.trialSequenceValues
  commentId: F:eDIA.ExperimentManager.ExperimentConfig.trialSequenceValues
  id: trialSequenceValues
  parent: eDIA.ExperimentManager.ExperimentConfig
  langs:
  - csharp
  - vb
  name: trialSequenceValues
  nameWithType: ExperimentManager.ExperimentConfig.trialSequenceValues
  fullName: eDIA.ExperimentManager.ExperimentConfig.trialSequenceValues
  type: Field
  source:
    id: trialSequenceValues
    path: ''
    startLine: 516
  assemblies:
  - cs.temp.dll
  namespace: eDIA
  syntax:
    content: public List<ExperimentManager.TrialSequenceValues> trialSequenceValues
    return:
      type: Global.List{eDIA.ExperimentManager.TrialSequenceValues}
    content.vb: Public trialSequenceValues As List(Of ExperimentManager.TrialSequenceValues)
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: eDIA.ExperimentManager.ExperimentConfig.hasBlockIntroduction(System.Int32)
  commentId: M:eDIA.ExperimentManager.ExperimentConfig.hasBlockIntroduction(System.Int32)
  id: hasBlockIntroduction(System.Int32)
  parent: eDIA.ExperimentManager.ExperimentConfig
  langs:
  - csharp
  - vb
  name: hasBlockIntroduction(Int32)
  nameWithType: ExperimentManager.ExperimentConfig.hasBlockIntroduction(Int32)
  fullName: eDIA.ExperimentManager.ExperimentConfig.hasBlockIntroduction(System.Int32)
  type: Method
  source:
    id: hasBlockIntroduction
    path: ''
    startLine: 521
  assemblies:
  - cs.temp.dll
  namespace: eDIA
  summary: 'Does the given block have a introduction text defined '
  example: []
  syntax:
    content: public bool hasBlockIntroduction(int _blockNumber)
    parameters:
    - id: _blockNumber
      type: System.Int32
      description: ''
    return:
      type: System.Boolean
      description: Boolean True if any
    content.vb: Public Function hasBlockIntroduction(_blockNumber As Integer) As Boolean
  overload: eDIA.ExperimentManager.ExperimentConfig.hasBlockIntroduction*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: eDIA.ExperimentManager.ExperimentConfig.GetBlockIntroduction(System.Int32)
  commentId: M:eDIA.ExperimentManager.ExperimentConfig.GetBlockIntroduction(System.Int32)
  id: GetBlockIntroduction(System.Int32)
  parent: eDIA.ExperimentManager.ExperimentConfig
  langs:
  - csharp
  - vb
  name: GetBlockIntroduction(Int32)
  nameWithType: ExperimentManager.ExperimentConfig.GetBlockIntroduction(Int32)
  fullName: eDIA.ExperimentManager.ExperimentConfig.GetBlockIntroduction(System.Int32)
  type: Method
  source:
    id: GetBlockIntroduction
    path: ''
    startLine: 535
  assemblies:
  - cs.temp.dll
  namespace: eDIA
  summary: Get the string value for blockintroduction of given blocknumber
  example: []
  syntax:
    content: public string GetBlockIntroduction(int _blockNumber)
    parameters:
    - id: _blockNumber
      type: System.Int32
      description: ''
    return:
      type: System.String
      description: Introduction text as string
    content.vb: Public Function GetBlockIntroduction(_blockNumber As Integer) As String
  overload: eDIA.ExperimentManager.ExperimentConfig.GetBlockIntroduction*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: eDIA
  commentId: N:eDIA
  name: eDIA
  nameWithType: eDIA
  fullName: eDIA
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Int32
  commentId: T:System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: Global.List{eDIA.ExperimentManager.SettingsTuple}
  commentId: '!:Global.List{eDIA.ExperimentManager.SettingsTuple}'
  definition: Global.List`1
  name: List<ExperimentManager.SettingsTuple>
  nameWithType: List<ExperimentManager.SettingsTuple>
  fullName: List<eDIA.ExperimentManager.SettingsTuple>
  nameWithType.vb: List(Of ExperimentManager.SettingsTuple)
  fullName.vb: List(Of eDIA.ExperimentManager.SettingsTuple)
  name.vb: List(Of ExperimentManager.SettingsTuple)
  spec.csharp:
  - uid: Global.List`1
    name: List
    nameWithType: List
    fullName: List
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - uid: eDIA.ExperimentManager.SettingsTuple
    name: ExperimentManager.SettingsTuple
    nameWithType: ExperimentManager.SettingsTuple
    fullName: eDIA.ExperimentManager.SettingsTuple
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: Global.List`1
    name: List
    nameWithType: List
    fullName: List
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - uid: eDIA.ExperimentManager.SettingsTuple
    name: ExperimentManager.SettingsTuple
    nameWithType: ExperimentManager.SettingsTuple
    fullName: eDIA.ExperimentManager.SettingsTuple
  - name: )
    nameWithType: )
    fullName: )
- uid: Global.List`1
  isExternal: true
  name: List<>
  nameWithType: List<>
  fullName: List<>
  nameWithType.vb: List(Of )
  fullName.vb: List(Of )
  name.vb: List(Of )
  spec.csharp:
  - uid: Global.List`1
    name: List
    nameWithType: List
    fullName: List
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - name: ''
    nameWithType: ''
    fullName: ''
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: Global.List`1
    name: List
    nameWithType: List
    fullName: List
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: ''
    nameWithType: ''
    fullName: ''
  - name: )
    nameWithType: )
    fullName: )
- uid: Global.List{System.Int32}
  commentId: '!:Global.List{System.Int32}'
  definition: Global.List`1
  name: List<Int32>
  nameWithType: List<Int32>
  fullName: List<System.Int32>
  nameWithType.vb: List(Of Int32)
  fullName.vb: List(Of System.Int32)
  name.vb: List(Of Int32)
  spec.csharp:
  - uid: Global.List`1
    name: List
    nameWithType: List
    fullName: List
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - uid: System.Int32
    name: Int32
    nameWithType: Int32
    fullName: System.Int32
    isExternal: true
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: Global.List`1
    name: List
    nameWithType: List
    fullName: List
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - uid: System.Int32
    name: Int32
    nameWithType: Int32
    fullName: System.Int32
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: Global.List{System.String}
  commentId: '!:Global.List{System.String}'
  definition: Global.List`1
  name: List<String>
  nameWithType: List<String>
  fullName: List<System.String>
  nameWithType.vb: List(Of String)
  fullName.vb: List(Of System.String)
  name.vb: List(Of String)
  spec.csharp:
  - uid: Global.List`1
    name: List
    nameWithType: List
    fullName: List
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: Global.List`1
    name: List
    nameWithType: List
    fullName: List
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: Global.List{eDIA.ExperimentManager.TrialSequenceValues}
  commentId: '!:Global.List{eDIA.ExperimentManager.TrialSequenceValues}'
  definition: Global.List`1
  name: List<ExperimentManager.TrialSequenceValues>
  nameWithType: List<ExperimentManager.TrialSequenceValues>
  fullName: List<eDIA.ExperimentManager.TrialSequenceValues>
  nameWithType.vb: List(Of ExperimentManager.TrialSequenceValues)
  fullName.vb: List(Of eDIA.ExperimentManager.TrialSequenceValues)
  name.vb: List(Of ExperimentManager.TrialSequenceValues)
  spec.csharp:
  - uid: Global.List`1
    name: List
    nameWithType: List
    fullName: List
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - uid: eDIA.ExperimentManager.TrialSequenceValues
    name: ExperimentManager.TrialSequenceValues
    nameWithType: ExperimentManager.TrialSequenceValues
    fullName: eDIA.ExperimentManager.TrialSequenceValues
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: Global.List`1
    name: List
    nameWithType: List
    fullName: List
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - uid: eDIA.ExperimentManager.TrialSequenceValues
    name: ExperimentManager.TrialSequenceValues
    nameWithType: ExperimentManager.TrialSequenceValues
    fullName: eDIA.ExperimentManager.TrialSequenceValues
  - name: )
    nameWithType: )
    fullName: )
- uid: eDIA.ExperimentManager.ExperimentConfig.hasBlockIntroduction*
  commentId: Overload:eDIA.ExperimentManager.ExperimentConfig.hasBlockIntroduction
  name: hasBlockIntroduction
  nameWithType: ExperimentManager.ExperimentConfig.hasBlockIntroduction
  fullName: eDIA.ExperimentManager.ExperimentConfig.hasBlockIntroduction
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: eDIA.ExperimentManager.ExperimentConfig.GetBlockIntroduction*
  commentId: Overload:eDIA.ExperimentManager.ExperimentConfig.GetBlockIntroduction
  name: GetBlockIntroduction
  nameWithType: ExperimentManager.ExperimentConfig.GetBlockIntroduction
  fullName: eDIA.ExperimentManager.ExperimentConfig.GetBlockIntroduction
