apiRules:
- include:
    uidRegex: ^eDIA
    type: Namespace
- include:
    uidRegex: ^TASK
    type: Namespace
- include:
    uidRegex: ^Global
    type: Namespace
- exclude:
    uidRegex: .*
    type: Namespace